### ISSUE TITLE
im stuck on #[EB|LOG:EXITBS:START] i have the same specs

### ISSUE THREAD

**Issue by UsetUset2244** [LeDevChiant/Hackintosh-Dell-G15-5510#1]
please help me @LeDevChiant i have same as your specs how do i get through this

**Comment by alxsbrz** [comment]
add me on discord i Will help you : BernardoDiCaprio#1505


Le ven. 28 avr. 2023 à 19:39, UsetUset2244 ***@***.***> a
écrit :

**Comment by UsetUset2244** [comment]
ok

**Comment by UsetUset2244** [comment]
i sent you a firiend request

**Comment by UsetUset2244** [comment]
sorry i noticed that you have mux switch in your laptop so you can switch to the intel cpu which is supported yes i have the same specs but no mux switch so i cant install macos im gonna mark this as closed
